### ISSUE TITLE
좋긴한데요...

### ISSUE THREAD

**Issue by sleepylion99** [falsy/delivery-tracking-for-whale#1]
택배 업체 들을 리스트로 처리하고
리스트에서 택배 업체들을 골라서
조회 할수 있게끔 하면 보기 좋을 거같아요

**Comment by falsy** [comment]
안녕하세요, @sleepylion99님.
말씀해주신 부분 참고하여 수정 반영하도록 하겠습니다.
좋은 의견 주셔서 감사합니다 :)
