### ISSUE TITLE
조회가 안됨

### ISSUE THREAD

**Issue by sleepylion99** [falsy/delivery-tracking-for-whale#9]
기존방식(새창)으로는 조회가 되는데 이번 방식 꺼는뭐라고 뜨면서 조회가 안됩니다
정확하게 보지않아서 모르겠지만 연결 안됐다는 문장 였던거 같습니다.
확인 부탁드립니다.

**Comment by falsy** [comment]
@sleepylion99 
안녕하세요, 이번에 추가된 조회는 [tracker.delivery](https://github.com/shlee322/delivery-tracker)에서 무료로 제공하는 API를 사용하고 있는데요.
직접 API 서버를 개발하는 건 시간적으로 어려움이 있어, 조회가 되지 않는 택배사를 말씀해 주시면 문제의 부분을 확인, 수정하여 해당 서비스에 풀 리퀘스트 해보도록 하겠습니다.
감사합니다 :)
